//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFSchoolManagement
{
    using System;
    
    public enum TeacherType : int
    {
        Permanent = 1,
        Contract = 2,
        Guest = 3
    }
}
